# Generated by Django 5.0.6 on 2024-09-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torq', '0002_rename_pasword_registration_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
