# Generated by Django 5.1.1 on 2024-10-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torq', '0003_alter_registration_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='profile',
        ),
        migrations.AddField(
            model_name='registration',
            name='image',
            field=models.ImageField(default=1, upload_to='user/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
    ]
