# Generated by Django 5.1.1 on 2024-10-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torq', '0005_remove_registration_gender_registration_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('CUSTOMER', 'customer'), ('SELLER', 'seller')], max_length=10, null=True),
        ),
    ]
