# Generated by Django 5.1.1 on 2024-10-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torq', '0006_alter_registration_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='user/')),
                ('role', models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('CUSTOMER', 'customer'), ('SELLER', 'seller')], max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='company',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
