# Generated by Django 5.1.1 on 2024-10-11 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torq', '0008_delete_products_alter_registration_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='service_pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='service_tb',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('regular', 'Regular'), ('emergency', 'Emergency')], max_length=20)),
                ('service_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('service_date', models.DateField()),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('service_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=20)),
                ('service_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_time', models.TimeField()),
                ('pay_status', models.CharField(default='NOT PAID', max_length=20)),
                ('service_pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torq.service_pro')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torq.registration')),
            ],
        ),
    ]
